# Use Node.js LTS as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install server dependencies
RUN npm install

# Copy the rest of the server code to the working directory
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose the port the server will run on
EXPOSE 5000

# Start the server
CMD ["node", "index.js"]